"""Before/after examples for the TTS text preprocessor (Pallika, report evidence).

Run from the repo root:  python backend/scripts/demo_text_preprocessor.py
Writes a markdown table to outputs/benchmarks/tts_expansion_examples.md
"""

import sys
from pathlib import Path

BACKEND_DIR = Path(__file__).resolve().parents[1]
if str(BACKEND_DIR) not in sys.path:
    sys.path.insert(0, str(BACKEND_DIR))

from app.tts.text_preprocessor import preprocess  # noqa: E402
from app.tts.tts_config import VOICE_MAP  # noqa: E402

CASES = [
    ("physics", "The equation v² = u² + 2as relates velocity and displacement."),
    ("physics", "A force of 20 N acting on 4 kg gives an acceleration of 5 m/s2."),
    ("physics", r"Newton's law of gravitation is F = G \frac{m_1 m_2}{r^2}."),
    ("physics", "The angle θ is measured from the normal, and Δp equals the impulse."),
    ("physics", "Kinetic energy is ½mv², measured in J, while power is measured in W."),
    ("chemistry", "When CH4 burns in O2 it forms CO2 and H2O."),
    ("chemistry", "NaCl(aq) + AgNO3(aq) → AgCl(s) + NaNO3(aq)"),
    ("chemistry", "A tertiary halide follows the SN1 pathway, not SN2."),
    ("chemistry", "Concentrated H2SO4 dehydrates C2H5OH at 443 K."),
    ("chemistry", "The equilibrium N2 + 3H2 ⇌ 2NH3 is exothermic."),
    ("biology", "Bacteria have 70S ribosomes, NOT 80S ribosomes."),
    ("biology", "DNA polymerase adds nucleotides in the 5' to 3' direction."),
    ("biology", "During the light reaction, NADP is reduced to NADPH and ATP is formed."),
    ("biology", "mRNA carries the codon, while tRNA carries the anticodon."),
    ("biology", "The F1 generation was self-pollinated to obtain the F2 generation."),
]


def main() -> None:
    # Windows consoles default to cp1252, which cannot print Greek or maths glyphs.
    try:
        sys.stdout.reconfigure(encoding="utf-8")
    except Exception:
        pass

    rows = []
    print("=" * 78)
    print("TTS TEXT PREPROCESSOR — BEFORE / AFTER")
    print("=" * 78)

    current_subject = None
    for subject, raw in CASES:
        if subject != current_subject:
            print(f"\n--- {subject.upper()} ---")
            current_subject = subject

        emphasis = VOICE_MAP.get(subject, {}).get("emphasis_words")
        spoken = preprocess(raw, subject, emphasis_words=emphasis)
        print(f"  IN : {raw}")
        print(f"  OUT: {spoken}\n")
        rows.append((subject, raw, spoken))

    out_dir = BACKEND_DIR / "outputs" / "benchmarks"
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / "tts_expansion_examples.md"

    lines = [
        "# TTS Formula & Notation Expansion Examples",
        "",
        "Generated by `backend/scripts/demo_text_preprocessor.py`.",
        "",
        "| Subject | Raw script text | Text sent to Edge-TTS |",
        "| --- | --- | --- |",
    ]
    for subject, raw, spoken in rows:
        raw_cell = raw.replace("|", "\\|")
        spoken_cell = spoken.replace("|", "\\|")
        lines.append(f"| {subject} | `{raw_cell}` | {spoken_cell} |")
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(f"Markdown table written to {out_path}")


if __name__ == "__main__":
    main()
