import logging
from typing import Any, Dict, List, Optional, Union
from pydantic import BaseModel, Field
from sentence_transformers import SentenceTransformer

from app.core.config import get_settings
from app.database.qdrant import QdrantDatabase, qdrant_db
from app.utils.chunk_logger import ChunkLogger, ExtractedChunk, chunk_logger

logger = logging.getLogger("textbook_rag.retriever")


class RetrievalResult(BaseModel):
    """Encapsulates the complete result of a RAG retrieval operation."""
    query: str
    chunks: List[ExtractedChunk]
    context_text: str = Field(default="", description="Assembled context text formatted for LLM prompts")
    answer: Optional[str] = Field(default=None, description="Grounded answer generated by LLM (Gemini)")
    total_chunks: int = 0
    top_score: float = 0.0
    filters_applied: Dict[str, Any] = Field(default_factory=dict)
    log_file_path: str = ""


class TextbookRetriever:
    """Retrieves grounded textbook chunks from Qdrant and logs all extractions to file."""

    def __init__(
        self,
        database: Optional[QdrantDatabase] = None,
        logger_instance: Optional[ChunkLogger] = None,
    ) -> None:
        self.settings = get_settings()
        self.database = database or qdrant_db
        self.logger = logger_instance or chunk_logger
        self._embedder: Optional[SentenceTransformer] = None

    def get_embedder(self) -> SentenceTransformer:
        """Lazily initialize the sentence transformer embedding model."""
        if self._embedder is None:
            model_name = self.settings.embedding_model or "all-MiniLM-L6-v2"
            logger.info(f"Loading embedding model: {model_name}")
            self._embedder = SentenceTransformer(model_name)
        return self._embedder

    def embed_query(self, query: str) -> List[float]:
        """Compute dense embedding vector for a query string."""
        embedder = self.get_embedder()
        vector = embedder.encode(query, normalize_embeddings=True)
        return vector.tolist()

    def assemble_context(self, chunks: List[ExtractedChunk]) -> str:
        """Format retrieved chunks into a coherent prompt context string."""
        if not chunks:
            return ""

        context_blocks = []
        for idx, chunk in enumerate(chunks, start=1):
            src_header = (
                f"[Source {idx}: Class {chunk.class_level or 'N/A'} {chunk.subject or 'N/A'} - "
                f"Ch {chunk.chapter_number or 'N/A'} ({chunk.chapter_name or 'N/A'}) | "
                f"Section: {chunk.section or 'General'}]"
            )
            block = f"{src_header}\n{chunk.content.strip()}"
            context_blocks.append(block)

        return "\n\n".join(context_blocks)

    def retrieve(
        self,
        query: str,
        top_k: int = 5,
        subject: Optional[str] = None,
        class_level: Optional[Union[str, int]] = None,
        chapter_number: Optional[Union[str, int]] = None,
        pdf_name: Optional[str] = None,
        score_threshold: Optional[float] = None,
        caller: Optional[str] = None,
        log_to_file: bool = True,
    ) -> RetrievalResult:
        """
        Retrieve textbook chunks matching query, logging all extracted chunks to a separate file.
        
        Args:
            query: The user's question or search query.
            top_k: Max chunks to extract.
            subject: Optional subject filter.
            class_level: Optional class level filter.
            chapter_number: Optional chapter filter.
            pdf_name: Optional source PDF filter.
            score_threshold: Optional minimum similarity threshold.
            caller: Optional caller identifier for logging.
            log_to_file: Whether to record results in the dedicated chunks log file.
            
        Returns:
            RetrievalResult containing extracted chunks, context text, and metadata.
        """
        filters = {
            "subject": subject,
            "class_level": class_level,
            "chapter_number": chapter_number,
            "pdf_name": pdf_name,
        }
        active_filters = {k: v for k, v in filters.items() if v is not None}

        chunks: List[ExtractedChunk] = []
        try:
            query_vector = self.embed_query(query)
            chunks = self.database.search_similar(
                query_vector=query_vector,
                top_k=top_k,
                subject=subject,
                class_level=class_level,
                chapter_number=chapter_number,
                pdf_name=pdf_name,
                score_threshold=score_threshold,
            )
        except Exception as exc:
            logger.error(f"Retrieval error for query '{query}': {exc}")
            raise ConnectionError(f"Database retrieval failed for query '{query}': {exc}") from exc

        # Always log extracted chunks (even if empty) to the dedicated log file
        if log_to_file:
            self.logger.log_retrieved_chunks(
                query=query,
                chunks=chunks,
                filters=active_filters,
                caller=caller or "TextbookRetriever",
            )

        context_text = self.assemble_context(chunks)
        top_score = max([c.score for c in chunks], default=0.0)

        return RetrievalResult(
            query=query,
            chunks=chunks,
            context_text=context_text,
            total_chunks=len(chunks),
            top_score=top_score,
            filters_applied=active_filters,
            log_file_path=str(self.logger.log_file_path),
        )


retriever = TextbookRetriever()
